# nftsets
nftset=/bmwusa.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fasebokk.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fasebook.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/faseboox.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/favebook.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/faycbok.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fb.careers/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fb.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fb.gg/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fb.me/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fb.watch/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fbacebook.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fbbmarket.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fbboostyourbusiness.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fbcdn.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fbcdn.net/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
nftset=/fbfeedback.com/4#inet#fw4#vpn4_m,6#inet#fw4#vpn6_m
