#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
CHAIN='lan2tproxy'
TABLE='tproxy'
MARK='0x198'
NFT='xui'

start_service() {
  nft "list table inet ${NFT}" >/dev/null 2>&1 || nft "add table inet ${NFT}"
  nft "list chain inet ${NFT} ${CHAIN}" >/dev/null 2>&1 ||
    nft "add chain inet ${NFT} ${CHAIN} { \
    type filter hook prerouting priority mangle+10; policy accept; \
  }"
  nft "add rule inet \
    ${NFT} ${CHAIN} \
    meta nfproto ipv4 \
    iifname \"br-lan.77\" \
    meta mark 0x100-0x115 \
    meta l4proto { tcp, udp } \
    counter meta mark set ${MARK} \
    tproxy ip to 127.0.0.1:10199"
  nft "add rule inet \
    ${NFT} ${CHAIN} \
    meta nfproto ipv6 \
    iifname \"br-lan.77\" \
    meta mark 0x100-0x115 \
    meta l4proto { tcp, udp } \
    counter meta mark set ${MARK} \
    tproxy ip6 to [::1]:10199"
  ip rule add fwmark ${MARK} table ${TABLE} priority 100
  ip route add local 0.0.0.0/0 dev lo table ${TABLE}
  ip -6 rule add fwmark ${MARK} table ${TABLE} priority 100
  ip -6 route add local ::/0 dev lo table ${TABLE}
}

stop_service() {
  nft "list table inet ${NFT}" >/dev/null 2>&1 && nft "delete table inet ${NFT}"
  ip rule del fwmark ${MARK} table ${TABLE} priority 100
  ip route del local 0.0.0.0/0 dev lo table ${TABLE}
  ip -6 rule del fwmark ${MARK} table ${TABLE} priority 100
  ip -6 route del local ::/0 dev lo table ${TABLE}
}
