#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
CHAIN='lan2tproxy'
TABLE='tproxy'
MARKS='0x100-0x115'
PORT='10199'
MARK='0x198'
NFT='xui'
LAN='br-lan.77'

start_service() {
  nft "list table inet ${NFT}" >/dev/null 2>&1 || nft "add table inet ${NFT}"
  nft "list chain inet ${NFT} ${CHAIN}" >/dev/null 2>&1 ||
    nft "add chain inet ${NFT} ${CHAIN} { \
    type filter hook prerouting priority mangle+10; policy accept; \
  }"
  # accept traffic to me:
  nft "add rule inet \
    ${NFT} ${CHAIN} \
    iifname ${LAN} \
    meta mark ${MARKS} \
    fib daddr type local \
    counter return"
  # all udp traffic to tproxy and replace tag:
  # nft "add rule inet ${NFT} ${CHAIN} iifname ${LAN} meta nfproto ipv4 \
  #   meta l4proto { udp } counter meta mark set ${MARK} tproxy ip to 127.0.0.1:${PORT}"
  # nft "add rule inet ${NFT} ${CHAIN} iifname ${LAN} meta nfproto ipv6 \
  #   meta l4proto { udp } counter meta mark set ${MARK} tproxy ip6 to [::1]:${PORT}"
  # all ipv6 traffic to tproxy and replace tag:
  nft "add rule inet ${NFT} ${CHAIN} iifname ${LAN} meta nfproto ipv6 \
    meta l4proto { tcp, udp } counter meta mark set ${MARK} tproxy ip6 to [::1]:${PORT}"
  # marked traffic to tproxy and replace tag:
  nft "add rule inet \
    ${NFT} ${CHAIN} \
    iifname ${LAN} \
    meta nfproto ipv4 \
    meta mark ${MARKS} \
    meta l4proto { tcp, udp } \
    counter meta mark set ${MARK} \
    tproxy ip to 127.0.0.1:${PORT}"
  nft "add rule inet \
    ${NFT} ${CHAIN} \
    iifname ${LAN} \
    meta nfproto ipv6 \
    meta mark ${MARKS} \
    meta l4proto { tcp, udp } \
    counter meta mark set ${MARK} \
    tproxy ip6 to [::1]:${PORT}"
  ip rule add fwmark ${MARK} table ${TABLE} priority 100
  ip route add local 0.0.0.0/0 dev lo table ${TABLE}
  ip -6 rule add fwmark ${MARK} table ${TABLE} priority 100
  ip -6 route add local ::/0 dev lo table ${TABLE}
}

stop_service() {
  nft "list table inet ${NFT}" >/dev/null 2>&1 && nft "delete table inet ${NFT}"
  ip rule del fwmark ${MARK} table ${TABLE} priority 100
  ip route del local 0.0.0.0/0 dev lo table ${TABLE}
  ip -6 rule del fwmark ${MARK} table ${TABLE} priority 100
  ip -6 route del local ::/0 dev lo table ${TABLE}
}
