#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
XUI_DB_FOLDER='/opt/3x-ui'

start_service() {
  procd_open_instance
  procd_set_param env \
    XUI_DB_FOLDER="${XUI_DB_FOLDER}" \
    XUI_BIN_FOLDER="${XUI_DB_FOLDER}/bin"
  procd_set_param stdout 1
  procd_set_param stderr 1
  # shellcheck disable=2086
  procd_set_param respawn \
    ${respawn_threshold:-333} \
    ${respawn_timeout:-3} \
    ${respawn_retry:-0}
  procd_set_param command bash -c "cd ${XUI_DB_FOLDER} && exec /usr/bin/prlimit \
    --nproc=32768:65536 --nofile=131072:524288 ${XUI_DB_FOLDER}/3x-ui 2>&1"
  # nproc not working for some reason:
  #procd_set_param limits nproc='32768 65536'
  # working, however already set by prlimit:
  #procd_set_param limits nofile='131072 524288'
  procd_close_instance
}

service_triggers() {
  procd_add_reload_trigger "3x-ui"
  procd_add_raw_trigger acme.renew 5000 /etc/init.d/3x-ui reload
}
