#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
XUI_DB_FOLDER='/opt/3x-ui'
CHAIN='lan2tproxy'
TABLE='tproxy'
MARK='0x198'

chain_add() {
  nft list chain inet fw4 "${CHAIN}" >/dev/null 2>&1 ||
    nft "add chain inet fw4 ${CHAIN} { \
    type filter hook prerouting priority mangle+10; policy accept; \
  }"
  nft "add rule inet \
    fw4 ${CHAIN} \
    meta nfproto ipv4 \
    iifname \"br-lan.77\" \
    meta mark 0x100-0x115 \
    meta l4proto { tcp, udp } \
    counter meta mark set ${MARK} \
    tproxy ip to 127.0.0.1:10199"
  nft "add rule inet \
    fw4 ${CHAIN} \
    meta nfproto ipv6 \
    iifname \"br-lan.77\" \
    meta mark 0x100-0x115 \
    meta l4proto { tcp, udp } \
    counter meta mark set ${MARK} \
    tproxy ip6 to [::1]:10199"
  ip rule add fwmark ${MARK} table ${TABLE} priority 100
  ip route add local 0.0.0.0/0 dev lo table ${TABLE}
  ip -6 rule add fwmark ${MARK} table ${TABLE} priority 100
  ip -6 route add local ::/0 dev lo table ${TABLE}
}
chain_del() {
  nft list chain inet fw4 "${CHAIN}" >/dev/null 2>&1 &&
    nft delete chain inet fw4 "${CHAIN}"
  ip rule del fwmark ${MARK} table ${TABLE} priority 100
  ip route del local 0.0.0.0/0 dev lo table ${TABLE}
  ip -6 rule del fwmark ${MARK} table ${TABLE} priority 100
  ip -6 route del local ::/0 dev lo table ${TABLE}
}

start_service() {
  chain_add
  procd_open_instance
  procd_set_param env \
    XUI_DB_FOLDER="${XUI_DB_FOLDER}" \
    XUI_BIN_FOLDER="${XUI_DB_FOLDER}/bin"
  procd_set_param stdout 1
  procd_set_param stderr 1
  # shellcheck disable=2086
  procd_set_param respawn \
    ${respawn_threshold:-333} \
    ${respawn_timeout:-3} \
    ${respawn_retry:-33}
  procd_set_param command bash -c 'cd /opt/3x-ui && exec /opt/3x-ui/3x-ui 2>&1'
  procd_close_instance
}

stop_service() {
  chain_del
}
