#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
XUI_DB_FOLDER='/opt/3x-ui'
start_service() {
  procd_open_instance
  procd_set_param env \
    XUI_DB_FOLDER="${XUI_DB_FOLDER}" \
    XUI_BIN_FOLDER="${XUI_DB_FOLDER}/bin"
  procd_set_param stdout 1
  procd_set_param stderr 1
  # shellcheck disable=2086
  procd_set_param respawn \
    ${respawn_threshold:-333} \
    ${respawn_timeout:-3} \
    ${respawn_retry:-33}
  procd_set_param command bash -c 'cd /opt/3x-ui && exec /opt/3x-ui/3x-ui 2>&1'
  procd_close_instance
}
