#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
ATOP_DIR2RAW='/opt/var/log/atop'

start_service() {
  /usr/bin/env mkdir -vp "${ATOP_DIR2RAW}"
  procd_open_instance
  procd_set_param stdout 1
  procd_set_param stderr 1
  # shellcheck disable=2086
  procd_set_param respawn \
    ${respawn_threshold:-333} \
    ${respawn_timeout:-3} \
    ${respawn_retry:-0}
  procd_set_param command /usr/bin/atop -w "${ATOP_DIR2RAW}/raw_$(date '+%Y%m%d')" 600
  procd_close_instance
}
