#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param stdout 1
  procd_set_param stderr 1
  # shellcheck disable=2086
  procd_set_param respawn \
    ${respawn_threshold:-333} \
    ${respawn_timeout:-3} \
    ${respawn_retry:-33}
  procd_set_param command bash -c 'cd /opt/authelia && exec /opt/bin/authelia --config /etc/authelia.yaml 2>&1'
  procd_close_instance
}
