#!/bin/sh /etc/rc.common
# shellcheck disable=2034
STOP=10
START=95
USE_PROCD=1
start_service() {
  procd_open_instance
  procd_set_param stdout 1
  procd_set_param stderr 1
  # shellcheck disable=2086
  procd_set_param respawn \
    ${respawn_threshold:-333} \
    ${respawn_timeout:-3} \
    ${respawn_retry:-0}
  procd_set_param command \
    /opt/bin/tun2socks -device 'tun://tun2ray' \
    -proxy 'socks5://tun2socks:kWOGr2ysCA@127.0.0.1:19645'
  procd_close_instance
}
