# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: test build
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  test-build:
    name: test build
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: login to ghcr
        if: "github.ref == 'refs/heads/master'"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_WRITER }}
      - name: container image
        run: ./image.sh
      - name: build device images
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_WRITER }}
          WRT_OPKG_REPO: ${{ secrets.WRT_OPKG_REPO }}
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
        run: ./build.sh
      - name: release device images
        if: >-
          github.event_name == 'pull_request' ||
          (github.event_name == 'schedule' || github.event_name == 'push')
          && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: >
            branch [${{
              github.head_ref == '' && github.ref_name || github.head_ref
            }}] images
          draft: true
          allowUpdates: true
          tag: rel999
          artifacts: "upload/*"
          repo: "green-wise"
          token: "${{ secrets.REGISTRY_WRITER }}"
          body: >
            branch [${{
              github.head_ref == '' && github.ref_name || github.head_ref
            }}] images from recent commit by GitHub actions
  linters:
    name: check linters
    timeout-minutes: 11
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
