# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
name: test build
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  test-build:
    name: test build
    timeout-minutes: 33
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: login to ghcr
        if: "github.ref == 'refs/heads/master'"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_WRITER }}
      - name: container image
        run: ./image.sh
      - name: device image
        env:
          WRT_OPKG_REPO: ${{ secrets.WRT_OPKG_REPO }}
        run: ./build.sh
  linters:
    name: check linters
    timeout-minutes: 11
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
