# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: test build
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
jobs:
  container-image:
    name: container image
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: login to ghcr
        if: "github.ref == 'refs/heads/master'"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_WRITER }}
      - name: container image
        run: ./image.sh
  define-matrix:
    name: define matrix
    timeout-minutes: 11
    runs-on: ubuntu-latest
    outputs:
      matrix_list: ${{ steps.define-matrix.outputs.matrix_list }}
    steps:
      - name: checkout the repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true
      - name: define matrix
        id: define-matrix
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_WRITER }}
        run: |
          source ./matrix.sh
          echo "matrix_list=${JSON_LIST}" >> "${GITHUB_OUTPUT}"
  device-images:
    name: "[${{ matrix.element }}] image"
    timeout-minutes: 22
    needs: define-matrix
    strategy:
      fail-fast: false
      matrix:
        element: ${{ fromJSON(needs.define-matrix.outputs.matrix_list) }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: build [${{ matrix.element }}] image
        env:
          GITHUB_TOKEN: ${{ secrets.REGISTRY_WRITER }}
          WRT_OPKG_REPO: ${{ secrets.WRT_OPKG_REPO }}
          INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
        run: NAME2BUILD='${{ matrix.element }}' ./build.sh
      - name: release [${{ matrix.element }}] image
        if: >-
          github.event_name == 'pull_request' ||
          (github.event_name == 'schedule' || github.event_name == 'push')
          && github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          name: >
            branch [${{
              github.head_ref == '' && github.ref_name || github.head_ref
            }}] images
          draft: true
          allowUpdates: true
          tag: rel999
          artifacts: "upload/*"
          repo: "green-wise"
          token: "${{ secrets.REGISTRY_WRITER }}"
          body: >
            branch [${{
              github.head_ref == '' && github.ref_name || github.head_ref
            }}] images from recent commit by GitHub actions
  linters:
    name: check linters
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repos
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
